/*
 * Copyright (c) 2014, Banco de Mexico. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 * 
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 * 
 *   - Neither the name of Banco de Mexico or the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.studyscarlet.media.plotgraph.view;

import com.studyscarlet.media.plotgraph.interfaces.IController;
import com.studyscarlet.media.plotgraph.interfaces.IView;
import com.studyscarlet.media.plotgraph.model.GraphModel;
import com.studyscarlet.media.plotgraph.view.helper.Grafico;
import javax.swing.JComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * com.studyscarlet.media.plotgraph.view.GraphView:
 * Esta clase representa...
 *
 * @author Angel Emilio de Le&oacute;n Guti&eacute;rrez (angel.deleon@banxico.org.mx)
 * @version 1.0
 * @since 1.0
 */
public class GraphView extends javax.swing.JInternalFrame implements IView {

    /**
     * Para el logger
     */
    private static final Logger logger = LoggerFactory.getLogger(GraphView.class);
    
    /**
     * Para el serializado
     */
    private static final long serialVersionUID = -5267181253388280000L;
    
    /**
     * El canvas del Gráfico.
     */
    private Grafico grafico;
    
    /** 
     * Creates new form GraphView
     * @param model 
     */
    public GraphView() {       
        initComponents();
        this.grafico = new Grafico();
        jPanGraph.add(grafico, java.awt.BorderLayout.CENTER);
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanGraph = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanGraph.setPreferredSize(new java.awt.Dimension(240, 320));
        jPanGraph.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanGraph, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanGraph;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setListeners(IController controller) {
        
    }

    @Override
    public void showView() {
        if (!isVisible()) {
            setVisible(true);
        }
    }

    @Override
    public void hideView() {
        if (isVisible()) {
            setVisible(false);
        }
    }

    @Override
    public void cleanView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void destroyView() {
        hideView();
        dispose();
    }

    @Override
    public JComponent toComponent() {
        return this;
    }

    @Override
    public JComponent getMainComponent() {
        return this;
    }

    public Grafico getGrafico() {
        return grafico;
    }

}
